from PyQt5.QtWidgets import QWidget, QApplication
from screens.pantalla_inicio_ui import Ui_Form  # Import the UI class generated by Qt Designer
import sys

class PantallaInicio(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        # Instance of the UI class from Qt Designer
        self.ui = Ui_Form()
        self.ui.setupUi(self)  # Setup the UI

        # Additional functionality or connectors if needed
        self.setup_connections()

    def setup_connections(self):
        # Connect signals to slots here if needed, e.g., button clicks
        pass


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = PantallaInicio()  # Instantiate the window
    window.show()
    sys.exit(app.exec_())
